#!/usr/bin/env bash
#
# Summary: Generate a binary package name for the current platform
#
# Usage: pyenv binary package-name <version>
#
#   Prints a package name containing the Python version, platform and
#   architecture. Uses the macOS major version or the distro/system release.
#
set -e
[ -n "$PYENV_DEBUG" ] && set -x

if [ "$1" = "--complete" ]; then
  exec pyenv-install --list --bare
fi

if [ $# -ne 1 ]; then
  pyenv-help --usage binary-package-name >&2
  exit 1
fi

version="$1"
source "${BASH_SOURCE%/*}/../share/pyenv-binary/common.bash"
if ! is_name_safe "$version"; then
  echo "pyenv-binary: invalid version name \`${version}'" >&2
  exit 1
fi

version="$(pyenv-latest -f -k "$version")"
if ! is_name_safe "$version"; then
  echo "pyenv-binary: invalid version name \`${version}'" >&2
  exit 1
fi

source "${BASH_SOURCE%/*}/../share/pyenv-binary/platform.bash"
suffix="$(package_suffix "$os" "$distro" "$arch")"
printf '%s-%s\n' "$version" "$suffix"
