#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

if [ -n "$PYENV_VERSION" ]; then
# IFS=: versions=($(${PYENV_VERSION})) # this does not work on zsh without `setopt shwordsplit`.
  versions=($(echo "${PYENV_VERSION}" | tr ":" " "))
else
  PYENV_VERSION_FILE="$(pyenv-version-file)"
  IFS=: versions=($(pyenv-version-file-read "$PYENV_VERSION_FILE" || true))
  IFS=: PYENV_VERSION="${versions[*]}"
  export PYENV_VERSION
fi

if [ -z "$versions" ] || [ "$versions" = "system" ] ; then
  echo "system"
  exit
fi

for version in "${versions[@]}"; do
  PYENV_VERSION_PATH="${PYENV_ROOT}/versions/${version}"
  
  if [ ! -d "$PYENV_VERSION_PATH" ]; then
    echo "pyenv: version \`$version' is not installed" >&2
    exit 1
  fi
done

echo "${PYENV_VERSION}"
