#!/usr/bin/env bash
# Summary: Show the current Python version and its origin
#
# Shows the currently selected Python version and how it was
# selected. To obtain only the version string, use `pyenv
# version-name'.

set -e
[ -n "$PYENV_DEBUG" ] && set -x

IFS=: PYENV_VERSION_NAMES=($(pyenv-version-name))

for PYENV_VERSION_NAME in "${PYENV_VERSION_NAMES[@]}"; do
  echo "$PYENV_VERSION_NAME (set by $(pyenv-version-origin))"
done
