#!/usr/bin/env bash
# Summary: Show the current Python version
set -e
[ -n "$PYENV_DEBUG" ] && set -x

if [ -z "$PYENV_VERSION" ]; then
  PYENV_VERSION_FILE="$(pyenv-version-file)"
  PYENV_VERSION_NAME="$(pyenv-version-name)"
  PYENV_VERSION_ALIAS="$(pyenv-version-file-read-alias "$PYENV_VERSION_FILE" || true)"
fi

if [ -n "$PYENV_VERSION_ALIAS" ]; then
    echo "$PYENV_VERSION_ALIAS"
else
    echo "$PYENV_VERSION_NAME"
fi
