#!/usr/bin/env bash
# Usage: pyenv version-file-write [-f|--force] <file> <version> [...]
#
#   -f/--force    Don't verify that the versions exist

set -euo pipefail
[ -n "${PYENV_DEBUG:-}" ] && set -x

FORCE=""

while [[ $# -gt 0 ]]
do
    case "${1:-}" in
        -f|--force)
            FORCE=1
            shift
            ;;
        *)
            break
            ;;
    esac
done


PYENV_VERSION_FILE="${1:-}"
shift || true
versions=("$@")

if [ ${#versions[@]} -eq 0 ] || [ -z "${PYENV_VERSION_FILE:-}" ] || [ -z "${versions[0]:-}" ]; then
  echo "Usage: pyenv version-file-write [-f|--force] <file> <version> [...]" >&2
  exit 1
fi

# Make sure the specified version is installed.
[[ -z "${FORCE:-}" ]] && pyenv-prefix "${versions[@]}" >/dev/null

# Write the version out to disk.
# Create an empty file. Using "rm" might cause a permission error.
> "$PYENV_VERSION_FILE"
for version in "${versions[@]}"; do
  echo "$version" >> "$PYENV_VERSION_FILE"
done
