#!/usr/bin/env bash
# Summary: Explain how the current Python version is set
set -e
[ -n "$PYENV_DEBUG" ] && set -x

if [ -n "$PYENV_VERSION" ]; then
  echo "PYENV_VERSION environment variable"
else
  pyenv-version-file
fi
