#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec pyenv-versions --bare
fi

PYENV_VERSION=($@)
PYENV_VERSION_FILE="${PYENV_ROOT}/version"

if [ -n "$PYENV_VERSION" ]; then
  pyenv-version-file-write "$PYENV_VERSION_FILE" "${PYENV_VERSION[@]}"
else
  IFS=: PYENV_VERSION=($(
    pyenv-version-file-read "$PYENV_VERSION_FILE" ||
    pyenv-version-file-read "${PYENV_ROOT}/global" ||
    pyenv-version-file-read "${PYENV_ROOT}/default" ||
    echo system
  ))
  for version in "${PYENV_VERSION[@]}"; do
    echo "$version"
  done
fi
