#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec pyenv-versions --bare
fi

if [ -n "$1" ]; then
  export PYENV_VERSION="$1"
elif [ -z "$PYENV_VERSION" ]; then
  PYENV_VERSION="$(pyenv-version-name)"
fi

if [ "$PYENV_VERSION" = "system" ]; then
  PYTHON_PATH="$(pyenv-which python)"
  echo "${PYTHON_PATH%/*}"
  exit
fi

PYENV_PREFIX_PATH="${PYENV_ROOT}/versions/${PYENV_VERSION}"
if [ ! -d "$PYENV_PREFIX_PATH" ]; then
  echo "pyenv: version \`${PYENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$PYENV_PREFIX_PATH"
