#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  exec pyenv-rehash --complete
fi

shell="$(basename "$SHELL")"

# When pyenv shell integration is enabled, delegate to pyenv-rehash,
# then tell the shell to empty its command lookup cache.
pyenv-rehash

case "$shell" in
fish )
  or='; or'
  ;;
* )
  or='||'
  ;;
esac

echo "hash -r 2>/dev/null $or true"
