#!/usr/bin/env bash
# Summary: List hook scripts for a given pyenv command
# Usage: pyenv hooks <command>

set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

PYENV_COMMAND="$1"
if [ -z "$PYENV_COMMAND" ]; then
  pyenv-help --usage hooks >&2
  exit 1
fi

IFS=: hook_paths=($PYENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$PYENV_COMMAND"/*.bash; do
    echo "$script"
  done
done
shopt -u nullglob
