#!/usr/bin/env bash
# Usage: pyenv version-file-read <file>
set -e
[ -n "$PYENV_DEBUG" ] && set -x

VERSION_FILE="$1"

if [ -e "$VERSION_FILE" ]; then
  # Read the first word from the specified version file. Avoid reading it whole.
  IFS="${IFS}"$'\r'
  words=($(cut -b 1-1024 "$VERSION_FILE" | sed 's/^\s*\(\S\+\).*/\1/'))
  versions=("${words[@]}")

  if [ -n "${versions[*]}" ]; then
    validated_versions=()
    for version in "${versions[@]}"; do
      if [ "$version" = ".." ] || [[ $version == */* ]]; then
        echo "pyenv: invalid version in \`$VERSION_FILE'" >&2
      else
        validated_versions+=("$version")
      fi
    done
  fi
  if [ -n "${validated_versions[*]}" ]; then
    IFS=":"
    echo "${validated_versions[*]}"
    exit
  fi
fi

exit 1
