#!/usr/bin/env bash
# Summary: Display the version of pyenv
#
# Displays the version number of this pyenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$PYENV_DEBUG" ] && set -x

version="20160202"
git_revision=""

for source_dir in "${BASH_SOURCE%/*}" "$PYENV_ROOT"; do
  if cd "$source_dir" 2>/dev/null && git remote -v 2>/dev/null | grep -q pyenv; then
    git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
    git_revision="${git_revision#v}"
    [ -z "$git_revision" ] || break
  fi
done

echo "pyenv ${git_revision:-$version}"
