#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec pyenv-versions --bare
fi

PYENV_VERSIONS=($@)
PYENV_VERSION_FILE="${PYENV_ROOT}/version"

if [ -n "$PYENV_VERSIONS" ]; then
  pyenv-version-file-write "$PYENV_VERSION_FILE" "${PYENV_VERSIONS[@]}"
else
  IFS=: PYENV_VERSIONS=($(
    pyenv-version-file-read "$PYENV_VERSION_FILE" ||
    pyenv-version-file-read "${PYENV_ROOT}/global" ||
    pyenv-version-file-read "${PYENV_ROOT}/default" ||
    echo system
  ))
  for PYENV_VERSION in "${PYENV_VERSIONS[@]}"; do
    echo "$PYENV_VERSION"
  done
fi
