#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

VERSION_FILE="$1"

if [ -e "$VERSION_FILE" ]; then
  # Read and print the first non-whitespace word from the specified
  # version file.
  versions=()
  while read -a words; do
    word="${words[0]}"
    if [ -n "$word" ]; then
      length="${#versions[@]}"
      versions=("${versions[@]}" "$word")
    fi
  done < <( cat "$VERSION_FILE" && echo )

  if [ -n "$versions" ]; then
    {
      IFS=:
      echo "${versions[*]}"
    }
    exit
  fi
fi

exit 1
