#!/usr/bin/env bash
set -e

if [ "$1" = "--sh" ]; then
  sh=1
  shift
fi

if [ "$1" = "--no-sh" ]; then
  nosh=1
  shift
fi

shopt -s nullglob

{ for path in ${PATH//:/$'\n'}; do
    for command in "${path}/rbenv-"*; do
      command="${command##*rbenv-}"
      if [ -n "$sh" ]; then
        if [ ${command:0:3} = "sh-" ]; then
          echo ${command##sh-}
        fi
      elif [ -n "$nosh" ]; then
        if [ ${command:0:3} != "sh-" ]; then
          echo ${command##sh-}
        fi
      else
        echo ${command##sh-}
      fi
    done
  done
} | sort | uniq
