#!/usr/bin/env bash
# Summary: Show the current Ruby version and its origin
#
# Shows the current Ruby version and where it's set from. To obtain only the
# version string, use `rbenv version-name'.

set -e
[ -n "$RBENV_DEBUG" ] && set -x

echo "$(rbenv-version-name) (set by $(rbenv-version-origin))"
