#!/usr/bin/env bash -e

abs_dirname() {
  orig_dir=`pwd`
  path="$1"
  while [ -n "$path" ]; do
    cd `dirname "$path"`
    name=`basename "$path"`
    path=`readlink "$name" || true`
  done
  unset name path

  pwd
  cd "$orig_dir"
  unset orig_dir
}

bindir=`abs_dirname $0`
export PATH="$bindir:$PATH"

command="$1"
if [ -z "$command" ]; then
  echo "rbenv 0.1.0" >&2

else
  command_path="$(command -v "rbenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "rbenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
fi
