#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

version=0.3.0

cd "$RBENV_ROOT"
git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
git_revision="${git_revision#v}"

echo "rbenv ${git_revision:-$version}"
