#!/usr/bin/env bash -e

RBENV_VERSION="$(rbenv-version || true)"

hit_prefix="* "
miss_prefix="  "

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
fi

for path in "${HOME}/.rbenv/versions/"*; do
  if [ -d "$path" ]; then
    version="${path##*/}"

    if [ "$version" == "$RBENV_VERSION" ]; then
      echo "${hit_prefix}${version}"
    else
      echo "${miss_prefix}${version}"
    fi
  fi
done
