#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

# Provide rbenv completions
if [ "$1" = "--complete" ]; then
  exec rbenv shims --short
fi

RBENV_COMMAND="$1"
if [ -z "$RBENV_COMMAND" ]; then
  echo "usage: rbenv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

RBENV_COMMAND_PATH="$(rbenv-which "$RBENV_COMMAND")"
RBENV_BIN_PATH="${RBENV_COMMAND_PATH%/*}"

for script in $(rbenv-plugin-scripts exec); do
  source "$script"
done

shift 1
export PATH="${RBENV_BIN_PATH}:${PATH}"
exec -a "$RBENV_COMMAND" "$RBENV_COMMAND_PATH" "$@"
