#!/usr/bin/env bash -e

RBENV_VERSION="$1"
VERSION_FILE="${HOME}/.rbenv/default"
if [ -z "$RBENV_VERSION" ]; then
  if [[ -e "$VERSION_FILE" ]]; then
    cat "$VERSION_FILE"
  else
    echo "No default version configured - set with: rbenv default <version>"
  fi
else
  # Make sure the specified version is installed
  rbenv-prefix "$RBENV_VERSION" >/dev/null

  echo "$RBENV_VERSION" > "$VERSION_FILE"
fi
