#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

RBENV_VERSION="$1"
RBENV_VERSION_FILE=".rbenv-version"

if [ "$RBENV_VERSION" = "--unset" ]; then
  rm -f "$RBENV_VERSION_FILE"
elif [ -n "$RBENV_VERSION" ]; then
  rbenv-version-file-write "$RBENV_VERSION_FILE" "$RBENV_VERSION"
else
  rbenv-version-file-read "$RBENV_VERSION_FILE" ||
  { echo "rbenv: no local version configured for this directory"
    exit 1
  } >&2
fi
