#!/usr/bin/env bash
set -e

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(readlink "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export PATH="${libexec_path}:${PATH}"

command="$1"
case $command in
"" | "-h" | "--help")
  echo -e "rbenv 0.1.0\n$(rbenv-help)" >&2
  ;;
*)
  command_path="$(command -v "rbenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "rbenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
