#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

root="$RBENV_DIR"
while [ -n "$root" ]; do
  if [ -e "${root}/.rbenv-version" ]; then
    echo "${root}/.rbenv-version"
    exit
  fi
  root="${root%/*}"
done

GLOBAL_PATH="${RBENV_ROOT}/global"
DEFAULT_PATH="${RBENV_ROOT}/default"

if [ -e "$GLOBAL_PATH" ]; then
  echo "$GLOBAL_PATH"
elif [ -e "$DEFAULT_PATH" ]; then
  echo "$DEFAULT_PATH"
else
  echo "$GLOBAL_PATH"
fi
