#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(rbenv-version-name || true)"
fi

for path in "${RBENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    version="${path##*/}"

    if [ "$version" == "$current_version" ]; then
      echo "${hit_prefix}$(rbenv-version)"
    else
      echo "${miss_prefix}${version}"
    fi
  fi
done
