#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

VERSION_FILE="$1"

if [ -e "$VERSION_FILE" ]; then
  # Read and print the first non-whitespace word from the specified
  # version file.
  version=""
  while read -a words; do
    word="${words[0]}"
    if [ -z "$version" ] && [ -n "$word" ]; then
      version="$word"
    fi
  done < <( cat "$VERSION_FILE" && echo )

  if [ -n "$version" ]; then
    echo "$version"
    exit
  fi
fi

exit 1
