#!/usr/bin/env bash
# Usage: rbenv version-file-read <file>
set -e
[ -n "$RBENV_DEBUG" ] && set -x

VERSION_FILE="$1"

if [ -e "$VERSION_FILE" ]; then
  # Read the first non-whitespace word from the specified version file.
  # Be careful not to load it whole in case there's something crazy in it.
  words=( $(cut -b 1-1024 "$VERSION_FILE") )
  version="${words[0]}"

  if [ -n "$version" ]; then
    echo "$version"
    exit
  fi
fi

exit 1
