#!/usr/bin/env bash
# Summary: Display the version of rbenv
#
# Displays the current revision info of rbenv from git if available, or falls
# back to the version of the last release.
#
# The format of the git revision is:
#   ${version}-${num_commits}-g${git_sha}
# where `num_commits` is the number of commits since `version` was tagged.

set -e
[ -n "$RBENV_DEBUG" ] && set -x

version=0.3.0

cd "$RBENV_ROOT"
git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
git_revision="${git_revision#v}"

echo "rbenv ${git_revision:-$version}"
