#!/usr/bin/env bash
set -e

if [ -n "$1" ]; then
  RBENV_VERSION="$1"
elif [ -z "$RBENV_VERSION" ]; then
  RBENV_VERSION="$(rbenv-version-name)"
fi

if [ "$RBENV_VERSION" = "system" ]; then
  RUBY_PATH="$(rbenv-which ruby)"
  echo "${RUBY_PATH%/*}"
  exit
fi

RBENV_PREFIX_PATH="${RBENV_HOME}/versions/${RBENV_VERSION}"
if [ ! -d "$RBENV_PREFIX_PATH" ]; then
  echo "rbenv: version \`${RBENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$RBENV_PREFIX_PATH"
