#!/usr/bin/env bash
set -e

RBENV_COMMAND="$1"
if [ -z "$RBENV_COMMAND" ]; then
  echo "usage: rbenv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

RBENV_COMMAND_PATH="$(rbenv-which "$RBENV_COMMAND")"
RBENV_BIN_PATH="${RBENV_COMMAND_PATH%/*}"

shopt -s nullglob
RBENV_EXEC_PLUGINS=(/etc/rbenv.d/exec/*.bash ${HOME}/.rbenv/rbenv.d/exec/*.bash)
shopt -u nullglob

for script in ${RBENV_EXEC_PLUGINS[@]}; do
  source $script
done

shift 1
export PATH="${RBENV_BIN_PATH}:${PATH}"
exec -a "$RBENV_COMMAND" "$RBENV_COMMAND_PATH" "$@"
