name: build
on:
  push:
    branches: [master]
  pull_request: {}

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - macos-26-intel
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-python
        with:
          python-version: ${{ matrix.python-version }}

